#!/bin/sh

# Prepare configuration files for environment variable substitution.
ENV_NAMES="`env | awk -F '=' '{printf "$%s ", $1}'`"
for file in /etc/dovecot/*.template; do
	envsubst "${ENV_NAMES}" < "$file" > "`echo $file | awk -F '.template$' '{print $1}'`"
done

# Compile Sieve scripts.
for file in /var/lib/dovecot/sieve/*.sieve; do
	sievec "$file"
done

# Create required user and group.
addgroup --system --gid 5000 virtual
adduser --system --uid 5000 --ingroup virtual --home /var/mail/virtual virtual

# Run Dovecot daemon.
/usr/sbin/dovecot -F
