apiVersion: v1
kind: Service
metadata:
  name: znc
  namespace: chat
spec:
  type: NodePort
  selector:
    app: znc
  ports:
    - name: znc
      port: 6667
      nodePort: 6667
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: znc
  namespace: chat
spec:
  template:
    metadata:
      labels:
        app: znc
    spec:
      containers:
        - name: znc
          image: docker.deuill.org/chat/znc:1.6.5
          imagePullPolicy: Never
          env:
            - name: ZNC_HOSTNAME
              value: chat.deuill.org
            - name: ZNC_DATA_DIR
              value: /var/lib/znc
            - name: ZNC_USER_NICKNAME
              valueFrom:
                secretKeyRef:
                  name: znc-user
                  key: nickname
            - name: ZNC_USER_REALNAME
              valueFrom:
                secretKeyRef:
                  name: znc-user
                  key: realname
            - name: ZNC_USER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: znc-user
                  key: password
          ports:
            - containerPort: 6667
          volumeMounts:
            - name: znc
              mountPath: /var/lib/znc
            - name: cert
              mountPath: /etc/ssl/private/chat.deuill.org
              readOnly: true
      volumes:
        - name: znc
          hostPath:
            path: /opt/kubernetes/chat/znc
        - name: cert
          secret:
            secretName: chat-deuill-org-certificate
