#!/bin/sh

# Prepare configuration files for environment variable substitution.
ENV_NAMES="`env | awk -F '=' '{printf "$%s ", $1}'`"
for file in /etc/biboumi/*.template; do
	envsubst "${ENV_NAMES}" < "$file" > "`echo $file | awk -F '.template$' '{print $1}'`"
done

# Create required user and group.
addgroup --system biboumi
adduser --system --ingroup biboumi --home "$BIBOUMI_DATA_DIR" biboumi

chown -R biboumi:biboumi "$BIBOUMI_DATA_DIR"
sudo -u biboumi -- /usr/bin/biboumi /etc/biboumi/biboumi.cfg "$@"
