apiVersion: v1
kind: Service
metadata:
  name: dovecot
  namespace: mail
spec:
  type: NodePort
  selector:
    app: dovecot
  ports:
    - name: imap
      port: 143
      nodePort: 143
    - name: imaps
      port: 993
      nodePort: 993
---
apiVersion: v1
kind: Service
metadata:
  name: dovecot-sasl
  namespace: mail
spec:
  selector:
    app: dovecot
  ports:
    - name: sasl
      port: 3659
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: dovecot
  namespace: mail
data:
  00-empty.conf: ""
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: dovecot
  namespace: mail
spec:
  template:
    metadata:
      labels:
        app: dovecot
    spec:
      containers:
        - name: dovecot
          image: docker.deuill.org/mail/dovecot:2.2.27
          imagePullPolicy: Never
          env:
            - name: MAIL_HOSTNAME
              value: mail.deuill.org
            - name: DATABASE_HOST
              value: mariadb.default.svc.cluster.local
            - name: DATABASE_USER
              value: mail
            - name: DATABASE_NAME
              value: mail
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mail-database
                  key: password
          ports:
            - containerPort: 143
            - containerPort: 993
            - containerPort: 3659
          volumeMounts:
            - name: mail
              mountPath: /var/mail
            - name: dovecot-config
              mountPath: /etc/dovecot/conf.d
            - name: cert
              mountPath: /etc/ssl/private/mail.deuill.org
              readOnly: true
      volumes:
        - name: mail
          hostPath:
            path: /opt/kubernetes/mail/shared
        - name: dovecot-config
          configMap:
            name: dovecot
        - name: cert
          secret:
            secretName: mail-deuill-org-certificate
