apiVersion: v1
kind: Service
metadata:
  name: dovecot
  namespace: mail
spec:
  selector:
    app: dovecot
  ports:
    - name: imap
      port: 143
    - name: sasl
      port: 3659
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: dovecot
  namespace: mail
spec:
  template:
    metadata:
      labels:
        app: dovecot
    spec:
      containers:
        - name: dovecot
          image: docker.deuill.org/mail/dovecot
          imagePullPolicy: Never
          env:
            - name: DATABASE_HOST
              value: mariadb.default.svc.cluster.local
            - name: DATABASE_USER
              value: mail
            - name: DATABASE_NAME
              value: mail
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mail-database
                  key: password
          ports:
            - containerPort: 143
            - containerPort: 3659
          volumeMounts:
            - name: mail
              mountPath: /var/mail
      volumes:
        - name: mail
          hostPath:
            path: /opt/kubernetes/mail/shared
