apiVersion: v1
kind: Service
metadata:
  name: prosody
  namespace: chat
spec:
  type: NodePort
  selector:
    app: prosody
  ports:
    - name: c2s
      port: 5222
      nodePort: 5222
    - name: s2s
      port: 5269
      nodePort: 5269
    - name: component
      port: 5347
      nodePort: 5347
---
apiVersion: v1
kind: Service
metadata:
  name: prosody-http
  namespace: chat
spec:
  selector:
    app: prosody
  ports:
    - name: http
      port: 5280
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: prosody
  namespace: chat
data:
  deuill.org.cfg.lua: |
    VirtualHost "deuill.org"
      http_host = "chat.deuill.org"
      http_external_url = "https://chat.deuill.org/"
      certificate = "/etc/ssl/private/deuill.org/tls.crt"

      authentication = "imap"
      imap_auth_host = os.getenv("IMAP_AUTH_HOST") or "localhost"
      imap_auth_port = os.getenv("IMAP_AUTH_PORT") or 993

      auth_append_host = true
      auth_imap_ssl = {
          mode = "client",
          protocol = "tlsv1_2"
      }
    Component "chat.deuill.org" "muc"
      modules_enabled = {"muc_mam", "vcard_muc"}

      name = "The deuill.org chatroom server"
      certificate = "/etc/ssl/private/chat.deuill.org/tls.crt"

      restrict_room_creation = "local"
      max_history_messages = 100
    Component "chat.deuill.org" "http_upload"
      http_external_url = "https://chat.deuill.org/"
      http_upload_expire_after = 60 * 60 * 24 * 7
      http_upload_file_size_limit = 1024 * 1024 * 32
      http_upload_quota = 1024 * 1024 * 1024
  biboumi.cfg.lua: |
    Component "biboumi"
      component_secret = os.getenv("BIBOUMI_PASSWORD") or ""
  spectrum.cfg.lua: |
    Component "spectrum-skype"
      component_secret = os.getenv("SPECTRUM_PASSWORD") or ""
    Component "spectrum-discord"
      component_secret = os.getenv("SPECTRUM_PASSWORD") or ""
    Component "spectrum-slack"
      component_secret = os.getenv("SPECTRUM_PASSWORD") or ""
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prosody
  namespace: chat
spec:
  selector:
    matchLabels:
      app: prosody
  template:
    metadata:
      labels:
        app: prosody
    spec:
      containers:
        - name: prosody
          image: docker.deuill.org/chat/prosody:0.11.7
          imagePullPolicy: Never
          env:
            - name: DATABASE_HOST
              value: mariadb.default.svc.cluster.local
            - name: DATABASE_NAME
              value: prosody
            - name: DATABASE_USERNAME
              value: prosody
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: prosody-database
                  key: password
            - name: IMAP_AUTH_HOST
              value: dovecot.mail.svc.cluster.local
            - name: IMAP_AUTH_PORT
              value: "993"
            - name: BIBOUMI_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: biboumi
                  key: server-password
            - name: SPECTRUM_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: spectrum
                  key: server-password
            - name: TURN_HOST
              value: turn.deuill.org
            - name: TURN_SECRET
              valueFrom:
                secretKeyRef:
                  name: coturn
                  key: static-secret
          ports:
            - containerPort: 5222
            - containerPort: 5269
            - containerPort: 5280
            - containerPort: 5347
          volumeMounts:
            - name: prosody-data
              mountPath: /var/lib/prosody
            - name: prosody-config
              mountPath: /etc/prosody/conf.d
            - name: deuill-org-cert
              mountPath: /etc/ssl/private/deuill.org
              readOnly: true
            - name: chat-deuill-org-cert
              mountPath: /etc/ssl/private/chat.deuill.org
              readOnly: true
      volumes:
        - name: prosody-data
          hostPath:
            path: /opt/kubernetes/chat/prosody
        - name: prosody-config
          configMap:
            name: prosody
        - name: deuill-org-cert
          secret:
            secretName: deuill-org-certificate
        - name: chat-deuill-org-cert
          secret:
            secretName: chat-deuill-org-certificate
