apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress
  namespace: chat
  annotations:
    certmanager.k8s.io/cluster-issuer: letsencrypt
    certmanager.k8s.io/acme-challenge-type: dns01
    certmanager.k8s.io/acme-dns01-provider: cloudflare-dns
    nginx.ingress.kubernetes.io/proxy-body-size: 8M
spec:
  tls:
    - secretName: chat-deuill-org-certificate
      hosts:
        - chat.deuill.org
  rules:
    - host: chat.deuill.org
      http:
        paths:
          - path: /
            backend:
              serviceName: prosody-http
              servicePort: 5280
