#!/bin/sh

# Run any database migrations needed.
php vendor/bin/phinx migrate

# Set up configuration, if needed.
php daemon.php config --username="$MOVIM_ADMIN" --password="$MOVIM_PASSWORD"

# Start Movim.
php daemon.php start --url="$MOVIM_DOMAIN" --port="$MOVIM_PORT" --interface="$MOVIM_INTERFACE" --verbose
