apiVersion: v1
kind: Service
metadata:
  name: coturn
  namespace: chat
spec:
  type: NodePort
  selector:
    app: coturn
  ports:
    # Base STUN/TURN ports.
    - protocol: UDP
      name: stun
      port: 3478
      nodePort: 3478
    - protocol: TCP
      name: stun-tcp
      port: 3478
      nodePort: 3478
    - protocol: UDP
      name: stuns
      port: 5349
      nodePort: 5349
    - protocol: TCP
      name: stuns-tcp
      port: 5349
      nodePort: 5349
    # Alternative STUN/TURN ports.
    - protocol: UDP
      name: stun-alt
      port: 3479
      nodePort: 3479
    - protocol: TCP
      name: stun-tcp-alt
      port: 3479
      nodePort: 3479
    - protocol: UDP
      name: stuns-alt
      port: 5350
      nodePort: 5350
    - protocol: TCP
      name: stuns-tcp-alt
      port: 5350
      nodePort: 5350
    # Relay ports.
    - protocol: UDP
      name: stun-relay-0
      port: 27000
      nodePort: 27000
    - protocol: UDP
      name: stun-relay-1
      port: 27001
      nodePort: 27001
    - protocol: UDP
      name: stun-relay-2
      port: 27002
      nodePort: 27002
    - protocol: UDP
      name: stun-relay-3
      port: 27003
      nodePort: 27003
    - protocol: UDP
      name: stun-relay-4
      port: 27004
      nodePort: 27004
    - protocol: UDP
      name: stun-relay-5
      port: 27005
      nodePort: 27005
    - protocol: UDP
      name: stun-relay-6
      port: 27006
      nodePort: 27006
    - protocol: UDP
      name: stun-relay-7
      port: 27007
      nodePort: 27007
    - protocol: UDP
      name: stun-relay-8
      port: 27008
      nodePort: 27008
    - protocol: UDP
      name: stun-relay-9
      port: 27009
      nodePort: 27009
    - protocol: UDP
      name: stun-relay-10
      port: 27010
      nodePort: 27010
    - protocol: UDP
      name: stun-relay-11
      port: 27011
      nodePort: 27011
    - protocol: UDP
      name: stun-relay-12
      port: 27012
      nodePort: 27012
    - protocol: UDP
      name: stun-relay-13
      port: 27013
      nodePort: 27013
    - protocol: UDP
      name: stun-relay-14
      port: 27014
      nodePort: 27014
    - protocol: UDP
      name: stun-relay-15
      port: 27015
      nodePort: 27015
    - protocol: UDP
      name: stun-relay-16
      port: 27016
      nodePort: 27016
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: coturn
  namespace: chat
spec:
  selector:
    matchLabels:
      app: coturn
  template:
    metadata:
      labels:
        app: coturn
    spec:
      containers:
        - name: coturn
          image: docker.deuill.org/chat/coturn:4.5.1.1
          imagePullPolicy: Never
          env:
            - name: COTURN_REALM
              value: chat.deuill.org
            - name: COTURN_REDIS_HOST
              value: redis.default.svc.cluster.local
            - name: COTURN_REDIS_DB
              value: "1"
            - name: COTURN_STATIC_AUTH_SECRET
              valueFrom:
                secretKeyRef:
                  name: coturn
                  key: static-secret
            - name: COTURN_CERTIFICATE_PATH
              value: /etc/ssl/private/chat.deuill.org/tls.crt
            - name: COTURN_PRIVATE_KEY_PATH
              value: /etc/ssl/private/chat.deuill.org/tls.key
          ports:
            # Base STUN/TURN ports.
            - protocol: TCP
              containerPort: 3478
            - protocol: UDP
              containerPort: 3478
            - protocol: TCP
              containerPort: 5349
            - protocol: UDP
              containerPort: 5349
            # Alternative STUN/TURN ports.
            - protocol: TCP
              containerPort: 3479
            - protocol: UDP
              containerPort: 3479
            - protocol: TCP
              containerPort: 5350
            - protocol: UDP
              containerPort: 5350
            # Relay ports.
            - protocol: UDP
              containerPort: 27000
            - protocol: UDP
              containerPort: 27001
            - protocol: UDP
              containerPort: 27002
            - protocol: UDP
              containerPort: 27003
            - protocol: UDP
              containerPort: 27004
            - protocol: UDP
              containerPort: 27005
            - protocol: UDP
              containerPort: 27006
            - protocol: UDP
              containerPort: 27007
            - protocol: UDP
              containerPort: 27008
            - protocol: UDP
              containerPort: 27009
            - protocol: UDP
              containerPort: 27010
            - protocol: UDP
              containerPort: 27011
            - protocol: UDP
              containerPort: 27012
            - protocol: UDP
              containerPort: 27013
            - protocol: UDP
              containerPort: 27014
            - protocol: UDP
              containerPort: 27015
            - protocol: UDP
              containerPort: 27016
          volumeMounts:
            - name: cert
              mountPath: /etc/ssl/private/chat.deuill.org
              readOnly: true
      volumes:
        - name: cert
          secret:
            secretName: chat-deuill-org-certificate
