apiVersion: v1
kind: Service
metadata:
  name: git-server
spec:
  type: NodePort
  selector:
    app: git-server
  ports:
    - name: ssh
      port: 22
      nodePort: 468
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: git-server
spec:
  selector:
    matchLabels:
      app: git-server
  template:
    metadata:
      labels:
        app: git-server
    spec:
      containers:
        - name: git-server
          image: docker.deuill.org/default/git-server:1.0.0
          imagePullPolicy: Never
          ports:
            - containerPort: 22
          volumeMounts:
            - name: git
              mountPath: /home/git
      volumes:
        - name: git
          hostPath:
            path: /opt/kubernetes/default/git
