apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: chat-deuill-org
  namespace: chat
spec:
  secretName: chat-deuill-org-certificate
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  commonName: chat.deuill.org
