apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: deuill-org
  namespace: chat
spec:
  secretName: deuill-org-certificate
  dnsNames:
    - deuill.org
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: letsencrypt

