apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: deuill-org
  namespace: chat
spec:
  secretName: deuill-org-certificate
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  commonName: deuill.org
  acme:
    config:
      - dns01:
          provider: cloudflare-dns
        domains:
          - deuill.org
