#!/bin/sh

# Prepare configuration files for environment variable substitution.
ENV_NAMES="`env | awk -F '=' '{printf "$%s ", $1}'`"
for file in /etc/radicale/*.template; do
	envsubst "${ENV_NAMES}" < "$file" > "`echo $file | awk -F '.template$' '{print $1}'`"
done

# Create required user and group.
addgroup --system radicale
adduser --system --ingroup radicale --home /var/lib/radicale radicale

chown -R radicale:radicale /var/lib/radicale
sudo -u radicale -- /usr/local/bin/radicale --config /etc/radicale/radicale.conf "$@"
