CREATE TABLE IF NOT EXISTS `users` (
	`username` VARCHAR(255) NOT NULL PRIMARY KEY,
	`password` VARCHAR(255) NOT NULL,
	`maildir` VARCHAR(255) NOT NULL,
	`home` VARCHAR(255) NOT NULL DEFAULT '/var/mail/virtual',
	`uid` SMALLINT(5) UNSIGNED NOT NULL DEFAULT 5000,
	`gid` SMALLINT(5) UNSIGNED NOT NULL DEFAULT 5000,
	`enabled` TINYINT(1) NOT NULL DEFAULT 1
);

CREATE TABLE IF NOT EXISTS `domains` (
	`id` SMALLINT(6) NOT NULL PRIMARY KEY AUTO_INCREMENT,
	`domain` VARCHAR(255) NOT NULL,
	`transport` VARCHAR(255) NOT NULL DEFAULT 'virtual:',
	`enabled` TINYINT(1) NOT NULL DEFAULT 1
);

CREATE TABLE `aliases` (
	`id` SMALLINT(3) NOT NULL PRIMARY KEY AUTO_INCREMENT,
	`mail` VARCHAR(255) NOT NULL,
	`destination` VARCHAR(255) NOT NULL,
	`enabled` TINYINT(1) NOT NULL DEFAULT 1,
	UNIQUE KEY `mail` (`mail`)
);
