apiVersion: v1
kind: Service
metadata:
  name: php-fpm
  namespace: web
spec:
  selector:
    app: php-fpm
  ports:
    - name: fastcgi
      port: 9000
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: php-fpm
  namespace: web
spec:
  template:
    metadata:
      labels:
        app: php-fpm
    spec:
      containers:
        - name: php-fpm
          image: docker.deuill.org/web/php-fpm
          imagePullPolicy: Never
          ports:
            - containerPort: 9000
