apiVersion: v1
kind: Service
metadata:
  name: navidrome
  namespace: web
spec:
  selector:
    app: navidrome
  ports:
    - name: http
      port: 80
      targetPort: 4533
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: navidrome
  namespace: web
spec:
  selector:
    matchLabels:
      app: navidrome
  template:
    metadata:
      labels:
        app: navidrome
    spec:
      containers:
        - name: navidrome
          image: docker.deuill.org/web/navidrome:0.31.0
          imagePullPolicy: Never
          ports:
            - containerPort: 4533
          volumeMounts:
            - name: data
              mountPath: /var/lib/navidrome
            - name: music
              mountPath: /opt/navidrome/music
      volumes:
        - name: data
          hostPath:
            path: /opt/kubernetes/web/navidrome
        - name: music
          hostPath:
            type: Directory
            path: /home/alex/Music
