apiVersion: v1
kind: Service
metadata:
  name: deuill-org
  namespace: web
spec:
  selector:
    app: deuill-org
  ports:
    - name: http
      port: 80
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: deuill-org
  namespace: web
data:
  deuill.org: |
    server {
      listen 80;
      server_name www.deuill.org;

      location / {
        return 301 https://deuill.org$request_uri;
      }
    }

    server {
      listen 80;
      server_name deuill.org;
      root /srv/http/deuill;

      include conf/basic.conf;
      include conf/site/generic.conf;
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deuill-org
  namespace: web
spec:
  selector:
    matchLabels:
      app: deuill-org
  template:
    metadata:
      labels:
        app: deuill-org
    spec:
      initContainers:
        - name: git
          image: docker.deuill.org/default/git-fetch:1.1.0
          imagePullPolicy: Never
          env:
            - name: GIT_REPOSITORY
              value: git@git-server.default.svc.cluster.local:deuill/deuill.org.git
            - name: GIT_REVISION
              value: 2017-09-02
            - name: GIT_ROOT
              value: /git/deuill
          volumeMounts:
            - name: ssh-key
              mountPath: /root/.ssh
            - name: deuill-org-source
              mountPath: /git
        - name: hugo
          image: docker.deuill.org/default/hugo:0.54.0
          imagePullPolicy: Never
          env:
            - name: HUGO_SOURCE
              value: /source/deuill
            - name: HUGO_DESTINATION
              value: /dest
          volumeMounts:
            - name: deuill-org-source
              mountPath: /source
            - name: deuill-org-dest
              mountPath: /dest
      containers:
        - name: nginx
          image: docker.deuill.org/web/nginx:1.17
          imagePullPolicy: Never
          ports:
            - containerPort: 80
          volumeMounts:
            - name: deuill-org-dest
              mountPath: /srv/http/deuill
            - name: deuill-org-config
              mountPath: /etc/nginx/sites-enabled
      volumes:
        - name: deuill-org-source
          emptyDir: {}
        - name: deuill-org-dest
          emptyDir: {}
        - name: deuill-org-config
          configMap:
            name: deuill-org
        - name: ssh-key
          secret:
            secretName: ssh-key
            defaultMode: 256
