apiVersion: v1
kind: Service
metadata:
  name: grawkit-deuill-org
  namespace: web
spec:
  selector:
    app: grawkit-deuill-org
  ports:
    - name: http
      port: 80
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grawkit-deuill-org
  namespace: web
spec:
  selector:
    matchLabels:
      app: grawkit-deuill-org
  template:
    metadata:
      labels:
        app: grawkit-deuill-org
    spec:
      containers:
        - name: grawkit
          image: deuill/grawkit-play:latest
          ports:
            - containerPort: 8080
