apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress
  namespace: web
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    nginx.ingress.kubernetes.io/proxy-body-size: 8M
spec:
  tls:
    - secretName: deuill-org-certificate
      hosts:
        - deuill.org
    - secretName: repository-deuill-org-certificate
      hosts:
        - repository.deuill.org
    - secretName: grawkit-deuill-org-certificate
      hosts:
        - grawkit.deuill.org
  rules:
    - host: deuill.org
      http:
        paths:
          - path: /
            backend:
              serviceName: deuill-org
              servicePort: 80
    - host: repository.deuill.org
      http:
        paths:
          - path: /
            backend:
              serviceName: repository-deuill-org
              servicePort: 80
    - host: grawkit.deuill.org
      http:
        paths:
          - path: /
            backend:
              serviceName: grawkit-deuill-org
              servicePort: 80
